"""empty message

Revision ID: 6e7972f48883
Revises: 
Create Date: 2021-11-01 18:50:11.686993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e7972f48883'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=512), nullable=True),
    sa.Column('first_name', sa.String(length=512), nullable=True),
    sa.Column('last_name', sa.String(length=512), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='social_media'
    )
    op.create_index(op.f('ix_social_media_user_account_email'), 'user_account', ['email'], unique=True, schema='social_media')
    op.create_table('account_authentication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=512), nullable=True),
    sa.Column('password_hash', sa.String(length=512), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=512), nullable=True),
    sa.Column('session_id', sa.String(length=512), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['social_media.user_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='social_media'
    )
    op.create_table('password_change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('old_password_hash', sa.String(length=512), nullable=True),
    sa.Column('new_password_hash', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=512), nullable=True),
    sa.Column('session_id', sa.String(length=512), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['social_media.user_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='social_media'
    )
    op.create_table('social_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=512), nullable=True),
    sa.Column('phone', sa.String(length=512), nullable=True),
    sa.Column('snap', sa.String(length=512), nullable=True),
    sa.Column('insta', sa.String(length=512), nullable=True),
    sa.Column('spotify', sa.String(length=512), nullable=True),
    sa.Column('linkedin', sa.String(length=512), nullable=True),
    sa.Column('facebook', sa.String(length=512), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['social_media.user_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='social_media'
    )
    op.create_index(op.f('ix_social_media_social_profile_email'), 'social_profile', ['email'], unique=True, schema='social_media')
    op.create_index(op.f('ix_social_media_social_profile_facebook'), 'social_profile', ['facebook'], unique=True, schema='social_media')
    op.create_index(op.f('ix_social_media_social_profile_insta'), 'social_profile', ['insta'], unique=True, schema='social_media')
    op.create_index(op.f('ix_social_media_social_profile_linkedin'), 'social_profile', ['linkedin'], unique=True, schema='social_media')
    op.create_index(op.f('ix_social_media_social_profile_phone'), 'social_profile', ['phone'], unique=True, schema='social_media')
    op.create_index(op.f('ix_social_media_social_profile_snap'), 'social_profile', ['snap'], unique=True, schema='social_media')
    op.create_index(op.f('ix_social_media_social_profile_spotify'), 'social_profile', ['spotify'], unique=True, schema='social_media')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_media_social_profile_spotify'), table_name='social_profile', schema='social_media')
    op.drop_index(op.f('ix_social_media_social_profile_snap'), table_name='social_profile', schema='social_media')
    op.drop_index(op.f('ix_social_media_social_profile_phone'), table_name='social_profile', schema='social_media')
    op.drop_index(op.f('ix_social_media_social_profile_linkedin'), table_name='social_profile', schema='social_media')
    op.drop_index(op.f('ix_social_media_social_profile_insta'), table_name='social_profile', schema='social_media')
    op.drop_index(op.f('ix_social_media_social_profile_facebook'), table_name='social_profile', schema='social_media')
    op.drop_index(op.f('ix_social_media_social_profile_email'), table_name='social_profile', schema='social_media')
    op.drop_table('social_profile', schema='social_media')
    op.drop_table('password_change', schema='social_media')
    op.drop_table('account_authentication', schema='social_media')
    op.drop_index(op.f('ix_social_media_user_account_email'), table_name='user_account', schema='social_media')
    op.drop_table('user_account', schema='social_media')
    # ### end Alembic commands ###
